### PR TITLE
Use dedicated runtime functions instead of relying on caml_ml_channels explicitly

### PR DESCRIPTION
**Pull request by hhugo**
This goes with https://github.com/ocsigen/js_of_ocaml/pull/1601 and should allow fixing memory leak of ocaml channels.

We first need a new release of jsoo that include the new api. We can then merge this PR (and release ppx_expect) and finally merge https://github.com/ocsigen/js_of_ocaml/pull/1601

### CODE REVIEW

**Comment by hhugo** [comment]
@tkluck-janestreet, @TyOverby, this PR blocks merging https://github.com/ocsigen/js_of_ocaml/pull/1601 (well, we would also need a new ppx_expect release)

**Comment by tkluck-janestreet** [comment]
hi @hhugo , just to let you know I forwarded this to the right people and they're looking at it. I'm sure they'll post an update here soon.

**Comment by dkalinichenko-js** [comment]
Hi, I'll submit a new release of `ppx_expect` once we review this internally.

**Comment by hhugo** [comment]
> Hi, I'll submit a new release of `ppx_expect` once we review this internally.
> 
> This might take some time, as we also need to update our internal version of `js_of_ocaml`.

Thank you

**Comment by rickyvetter** [comment]
There are some timing issues on this as we are using wasm_of_ocaml with some patches and https://github.com/ocsigen/js_of_ocaml/pull/1601 doesn't apply cleanly. I know @vouillon and Tarides folks are looking at getting wasm_of_ocaml up-to-date with jsoo, which would make this change quite straightforward. If that is happening in the next couple weeks then we would rather wait and then apply all of these changes after updating.

**Comment by hhugo** [comment]
> There are some timing issues on this as we are using wasm_of_ocaml with some patches and [ocsigen/js_of_ocaml#1601](https://github.com/ocsigen/js_of_ocaml/pull/1601) doesn't apply cleanly. I know @vouillon and Tarides folks are looking at getting wasm_of_ocaml up-to-date with jsoo, which would make this change quite straightforward. If that is happening in the next couple weeks then we would rather wait and then apply all of these changes after updating.

It's apparently not happening in the next couple of weeks

**Comment by rickyvetter** [comment]
These changes have been released internally and will be part of the next public release. Apologies for the delay here.

**Comment by dkalinichenko-js** [comment]
Thank you! https://github.com/ocaml/opam-repository/pull/26695 was submitted with this patch.

**Pull request merged**
