### PR TITLE
Allow expect_tests to be DCE by jsoo ..

### PR DESCRIPTION
**Pull request by hhugo**
when setting FORCE_DROP_INLINE_TEST

This fixes https://github.com/ocsigen/js_of_ocaml/issues/1625.
I'm not attached to the current implementation. In particular, one could share the logic with ppx_inline_test. I let you decide what to do.

cc @WardBrian

### CODE REVIEW

**Comment by hhugo** [comment]
gentle ping

**Comment by hhugo** [comment]
Has anyone looked at this ?

**Comment by hhugo** [comment]
@TyOverby, can you try to move this forward ?

**Comment by TyOverby** [comment]
Sorry, It looks like no one noticed this earlier, I've forwarded it to the owners of this library

**Comment by dvulakh** [comment]
Thanks for the report, and sorry that this got lost internally. We'll need to make this change using the interface exposed by the `ppx_inline_test` runtime-lib. I'll update once we've made the fix internally and I have an estimate for when it will be available here.

**Comment by hhugo** [comment]
Any progress ?

**Comment by TyOverby** [comment]
I took this over from @dvulakh yesterday and it should be ready soon.  Sorry for how long this has taken

**Comment by TyOverby** [comment]
the fix has been released and will be included in our next push to github.

**Comment by hhugo** [comment]
I see https://github.com/janestreet/ppx_expect/commit/c92337f2fc909d332649964e9f54d3641f445158 was pushed.
@TyOverby, Can you confirm this is enough to drop expect test with jsoo ?

**Comment by TyOverby** [comment]
Yes, this fixes the issue (at least it does on the version of wasm_of_ocaml that we were using last month, which should be pretty up to date)

**Pull request closed without merging**
