### PR TITLE
Fix regression for windows support in v0.17.0

### PR DESCRIPTION
**Pull request by hhugo**
This was already fixed in v0.14. See https://github.com/janestreet/ppx_expect/pull/35

### CODE REVIEW

**Comment by hhugo** [comment]
gentle ping

**Comment by hhugo** [comment]
Can someone take a look at this ?

**Comment by hhugo** [comment]
rebased

**Comment by hhugo** [comment]
@TyOverby, can you make sure someone sees this ?

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/26222
https://github.com/ocaml/opam-repository/pull/26734

**Comment by dkalinichenko-js** [comment]
I've submitted https://github.com/ocaml/opam-repository/pull/26739 with the fix, and it'll be also included in the v0.18 release. Sorry for the delay. If you want to make sure someone sees a request timely in the future, it would be best to ping me or to email [opensource-contacts@janestreet.com](mailto:opensource-contacts@janestreet.com).

**Pull request merged**
