### PR TITLE
Fix for windows

### LINKED ISSUE #34: Ppx_expect doesn't seem to work on windows
I'm trying to make expect_test work on windows for js_of_ocaml.
Here is what I get in https://github.com/ocsigen/js_of_ocaml/pull/1132

using `ppx_expect.v0.14.1`, `ppx_inline_test.v0.14.1`

`cat debug-expect/dune`

```
(library
 (name debug_expect)
 (inline_tests
  (modes js native))
 (preprocess (pps ppx_expect)))
```

`cat debug-expect/debug_expect.ml`

```ocaml
let%expect_test _ =
  print_endline "hello";
  [%expect {| hello |}]
```

```
Run opam exec -- dune runtest debug-expect
  opam exec -- dune runtest debug-expect
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    OPAMCOLOR: always
    OPAMERRLOGLEN: 0
    OPAMJOBS: 2
    OPAMPRECISETRACKING: 1
    OPAMSOLVERTIMEOUT: 1000
    OPAMVERBOSE: false
    OPAMYES: 1
    OPAMROOT: D:\.opam
    HOME: C:\Users\runneradmin
    MSYS: winsymlinks:native
    CYGWIN: winsymlinks:native
    CYGWIN_ROOT: D:\cygwin
    CYGWIN_ROOT_BIN: D:\cygwin\bin
    CYGWIN_ROOT_WRAPPERBIN: D:\cygwin\wrapperbin
    DUNE_CACHE: enabled
    DUNE_CACHE_TRANSPORT: direct
inline_test_runner_debug_expect alias debug-expect/runtest (exit 2)
(cd _build/default/debug-expect && .debug_expect.inline-tests/inline_test_runner_debug_expect.exe inline-test-runner debug_expect -source-tree-root .. -diff-cmd -)
File "debug-expect/debug_expect.ml", line 1, characters 0-70 threw End_of_file.
  Raised at Base__Exn.protectx in file "src/exn.ml", line 71, characters 4-114
  Called from Ppx_inline_test_lib__Runtime.time_and_reset_random_seeds in file "runtime-lib/runtime.ml", line 356, characters 15-52
  Called from Ppx_inline_test_lib__Runtime.test in file "runtime-lib/runtime.ml", line 444, characters 52-83

FAILED 1 / 1 tests
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by hhugo**
This is based on top of the latest release v0.14.1 because I would like a point release for it

Fix #34

### CODE REVIEW

**Comment by hhugo** [comment]
There seems to remain an issue on window. ppx_expect show diffs where it should not. maybe because of `\r\n`. I'll report back.

**Comment by hhugo** [comment]
I'm able to have my tests pass on windows with 
- this patch
- git configured with `core.eof lf` and `core.autocrlf false`

I believe a better/real support should be implemented at some point.
cc @dra27 @smorimoto

**Comment by hhugo** [comment]
I've vendored ppx_expect with this fix in jsoo https://github.com/ocsigen/js_of_ocaml/pull/1132

**Comment by hhugo** [comment]
@jeremiedimino, do you have time to look at this ? I'd love a point release so that I can remove the vendored version of ppx_expect in jsoo

**Comment by smorimoto** [comment]
I think we've discussed before that it's better to normalise the behavior of the quoted string itself in the sense of a real fix. Whatever the case, this missing issue is a real pain for making Windows support more widely available in my honest opinion.

**Comment by jeremiedimino** [comment]
What would be the proper fix?

/cc @ceastlund who know owns `ppx_expect`

**Comment by aalekseyev** [comment]
@hhugo, can you please sign-off your contribution as described in https://probot.github.io/apps/dco/ before we can merge it?

**Comment by aalekseyev** [comment]
Actually, I'll just go ahead and merge it since I know you meant it. Please do the formal signoff in the future.

**Comment by smorimoto** [comment]
Is there any plan to release v0.14.2?

**Comment by aalekseyev** [comment]
@cwong-ocaml ?

**Pull request merged**
